export const RAP_QUOTES = [
  '"Fogo nos racistas, é o mínimo que a gente pede." — Djonga',
  '"O topo é pouco, eu quero o controle do que é meu." — Djonga',
  '"Dinheiro é bom, mas a paz de espírito é melhor ainda." — BK\'',
  '"Se o amanhã não for nada disso, caberá a mim esquecer." — BK\'',
  '"Injustiça atrai a fúria e o que é nosso nós vai buscar." — Racionais MC\'s',
  '"Vivão e vivendo, a rua é nóis, não é brincadeira." — Racionais MC\'s',
  '"Sonhar vicia, parar de sonhar me dá abstinência." — Emicida',
  '"Hoje eu sou dono do meu próprio império." — Filipe Ret',
  '"Eles querem meu fim, mas eu nasci pra ser o começo." — L7NNON',
  '"Ninguém é igual a ninguém, e essa é a nossa maior arma." — BK\'',
  '"A vida é um sopro, então não perde tempo com besteira." — Matuê',
  '"Sigo invicto, meu amor, quem sabe o que planta não teme a colheita." — Filipe Ret',
  '"Nós é a luz no fim do túnel." — Djonga',
  '"Coragem é a resistência ao medo, não a ausência dele." — BK\'',
  '"Nas noites mais escuras, as estrelas brilham mais." — Racionais MC\'s',
  '"Minha mente é meu guia, meu coração meu motor." — Filipe Ret',
  '"Vim pra deixar o meu legado, não pra agradar otário." — Djonga',
  '"Sou minha própria inspiração." — L7NNON',
  '"Avisa lá que o morro desceu e não é carnaval." — Racionais MC\'s',
  '"Foco, força e fé. O resto a gente corre atrás." — Projota',
  '"A rua é noiz, o resto é boato." — Emicida',
  '"O mundo é um moinho, mas a gente mói de volta." — Djonga',
  '"Crescer custa caro, o tempo é o preço." — BK\'',
  '"Se o mundo acabar amanhã, me acorde ao meio-dia." — BK\'',
  '"Malandragem de verdade é viver." — Sabotage',
  '"Para quem tem fé, a vida nunca tem fim." — Racionais MC\'s',
  '"E se eu cair, eu me levanto mais forte." — Djonga',
  '"Não tem como voltar no tempo, então faz o agora." — BK\'',
  '"Só quem é de lá sabe o que acontece lá." — Racionais MC\'s',
  '"Eles querem que você desista, mas eu não vou dar esse gostinho." — Filipe Ret',
  '"Onde o filho chora e a mãe não vê." — Racionais MC\'s',
  '"Até o maior dos prédios começa no chão." — Emicida',
  '"Deixa eles falarem, eu tô fazendo a minha parte." — L7NNON',
  '"Quem não é visto, não é lembrado. E quem não corre, não alcança." — Racionais MC\'s',
  '"Eu não mudei, eu só aprendi a jogar o jogo." — Djonga',
  '"A fé move montanhas, mas a atitude traz elas até você." — BK\'',
  '"Seja a mudança que você quer ver no mundo." — Emicida',
  '"Não sou o dono do mundo, mas sou o filho do dono." — Racionais MC\'s',
  '"A vida me ensinou a nunca desistir, ganhar, perder mas procurar evoluir." — Charlie Brown Jr / Sabotage',
  '"Pra quem já não tinha nada, metade é o dobro." — Emicida',
  '"Cada cicatriz é a prova de que eu sobrevivi." — Djonga',
  '"Quem tem boca vai a Roma, quem tem visão constrói o império." — Filipe Ret',
  '"A mente é um labirinto, eu sou o minotauro." — BK\'',
  '"A vida é loka, nêgo, e nela eu tô de passagem." — Racionais MC\'s',
  '"A dor ensina mais que qualquer professor." — Djonga',
  '"Se você não tentar, já perdeu antes de começar." — L7NNON',
  '"O que é meu tá guardado, e ninguém tira." — Filipe Ret',
  '"Tudo que nós tem é nós, então vamo se amar." — Emicida',
  '"O topo é solitário, mas a vista é linda." — BK\'',
  '"Não há vitória sem luta, não há glória sem dor." — Racionais MC\'s',
  '"A persistência é o caminho do êxito." — Djonga',
  '"Não deixo ninguém apagar o meu brilho." — L7NNON',
  '"A vida é curta, a arte é longa." — Emicida',
  '"O impossível é só questão de opinião." — Chorão',
  '"Sempre fui sonhador, é isso que me mantém vivo." — Racionais MC\'s',
  '"Eles riem de mim porque sou diferente, eu rio deles porque são todos iguais." — Filipe Ret',
  '"O tempo é o senhor de tudo, ele revela quem é quem." — BK\'',
  '"O amanhã é um mistério, hoje é uma dádiva." — Emicida',
  '"Se eu não puder ser o melhor, serei inesquecível." — Djonga',
  '"Nunca subestime o poder da favela." — Racionais MC\'s',
  '"A rua cobra, mas também ensina." — BK\'',
  '"Se a vida é um jogo, eu vim pra zerar." — L7NNON',
  '"O silêncio é de ouro, a palavra é de prata." — Filipe Ret',
  '"A esperança é a última que morre, mas a primeira que nasce." — Emicida',
  '"Não importa de onde você vem, importa pra onde você vai." — Djonga',
  '"O conhecimento é a única riqueza que ninguém pode roubar." — Racionais MC\'s',
  '"Eu sou o mestre do meu destino, o capitão da minha alma." — BK\'',
  '"A humildade é a chave do sucesso." — Emicida',
  '"O choro pode durar uma noite, mas a alegria vem pela manhã." — Racionais MC\'s',
  '"Se a vida te der limões, faça uma caipirinha." — Filipe Ret',
  '"O céu é o limite, e nós já estamos voando." — L7NNON',
  '"A verdadeira força vem de dentro." — Djonga',
  '"O amor é a arma mais poderosa." — Emicida',
  '"Nunca abaixe a cabeça pra ninguém." — Racionais MC\'s',
  '"O respeito é a base de tudo." — BK\'',
  '"A vitória é doce, mas o caminho é amargo." — Djonga',
  '"Acredite em si mesmo, quando ninguém mais acreditar." — Filipe Ret',
  '"A vida é um palco, e eu sou o protagonista." — L7NNON',
  '"A justiça tarda, mas não falha." — Racionais MC\'s',
  '"O futuro pertence àqueles que acreditam na beleza de seus sonhos." — Emicida',
  '"Eu sou o que sou, e não o que os outros querem que eu seja." — BK\'',
  '"A paciência é uma virtude." — Djonga',
  '"O sucesso é a melhor vingança." — Filipe Ret',
  '"A gratidão é a memória do coração." — Emicida',
  '"A vida é feita de escolhas." — Racionais MC\'s',
  '"O medo é apenas uma ilusão." — L7NNON',
  '"A coragem não é a ausência de medo, mas a ação apesar dele." — BK\'',
  '"O destino não é uma questão de sorte, é uma questão de escolha." — Djonga',
  '"A vida é como andar de bicicleta. Para ter equilíbrio, você tem que se manter em movimento." — Emicida',
  '"O sucesso não é final, o fracasso não é fatal: é a coragem de continuar que conta." — Filipe Ret',
  '"A jornada de mil milhas começa com um único passo." — BK\'',
  '"O que não nos mata, nos torna mais fortes." — Djonga',
  '"A maior glória em viver não está em nunca cair, mas em nos levantar toda vez que caímos." — Emicida',
  '"O único lugar onde o sucesso vem antes do trabalho é no dicionário." — L7NNON',
  '"A vida é 10% o que acontece com você e 90% como você reage a isso." — Racionais MC\'s',
  '"A mente é tudo. O que você pensa, você se torna." — BK\'',
  '"O melhor momento para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora." — Djonga',
  '"Não espere por líderes; faça você mesmo, pessoa por pessoa." — Emicida',
  '"A educação é a arma mais poderosa que você pode usar para mudar o mundo." — Racionais MC\'s'
];

export const BIBLE_VERSES = [
  '"O Senhor é o meu pastor; nada me faltará." — Salmos 23:1',
  '"Tudo posso naquele que me fortalece." — Filipenses 4:13',
  '"Pois eu bem sei os planos que estou projetando para vós, diz o Senhor; planos de paz, e não de mal, para vos dar um futuro e uma esperança." — Jeremias 29:11',
  '"Se Deus é por nós, quem será contra nós?" — Romanos 8:31',
  '"Mas os que esperam no Senhor renovarão as suas forças e subirão com asas como águias." — Isaías 40:31',
  '"O Senhor é a minha luz e a minha salvação; a quem temerei?" — Salmos 27:1',
  '"Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento." — Provérbios 3:5',
  '"Deixo-vos a paz, a minha paz vos dou." — João 14:27',
  '"Ainda que eu ande pelo vale da sombra da morte, não temerei mal algum, porque tu estás comigo." — Salmos 23:4',
  '"Portanto, não vos inquieteis com o dia de amanhã, pois o amanhã trará os seus cuidados." — Mateus 6:34',
  '"O coração do homem planeja o seu caminho, mas o Senhor lhe dirige os passos." — Provérbios 16:9',
  '"Sede fortes e corajosos; não temais, nem vos assusteis para com eles." — Deuteronômio 31:6',
  '"Não fui eu que lhe ordenei? Seja forte e corajoso!" — Josué 1:9',
  '"Este é o dia que o Senhor fez; regozijemo-nos e alegremo-nos nele." — Salmos 118:24',
  '"Buscai primeiro o reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas." — Mateus 6:33',
  '"Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei." — Mateus 11:28',
  '"O amor é sofredor, é benigno; o amor não é invejoso; o amor não trata com leviandade, não se ensoberbece." — 1 Coríntios 13:4',
  '"Pois o Senhor, vosso Deus, é o que vai convosco, a pelejar contra os vossos inimigos, para salvar-vos." — Deuteronômio 20:4',
  '"Em paz também me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança." — Salmos 4:8',
  '"O choro pode durar uma noite, mas a alegria vem pela manhã." — Salmos 30:5',
  '"Elevo os olhos para os montes: de onde me virá o socorro? O meu socorro vem do Senhor, que fez o céu e a terra." — Salmos 121:1-2',
  '"Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia." — Salmos 46:1',
  '"Pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus." — Efésios 2:8',
  '"Ora, a fé é o firme fundamento das coisas que se esperam, e a prova das coisas que se não veem." — Hebreus 11:1',
  '"Não te deixes vencer do mal, mas vence o mal com o bem." — Romanos 12:21',
  '"Sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus." — Romanos 8:28',
  '"O Senhor te abençoe e te guarde; o Senhor faça resplandecer o seu rosto sobre ti." — Números 6:24-25',
  '"Não andeis ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, sejam as vossas petições conhecidas diante de Deus." — Filipenses 4:6',
  '"Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração." — Romanos 12:12',
  '"Deem graças ao Senhor, porque ele é bom; o seu amor dura para sempre." — Salmos 107:1',
  '"O que encobre as suas transgressões nunca prosperará, mas o que as confessa e deixa, alcançará misericórdia." — Provérbios 28:13',
  '"Sujeitai-vos, pois, a Deus, resisti ao diabo, e ele fugirá de vós." — Tiago 4:7',
  '"Lâmpada para os meus pés é tua palavra, e luz para o meu caminho." — Salmos 119:105',
  '"A resposta branda desvia o furor, mas a palavra dura suscita a ira." — Provérbios 15:1',
  '"Regozijai-vos sempre. Orai sem cessar. Em tudo dai graças." — 1 Tessalonicenses 5:16-18',
  '"O Senhor é bom, uma fortaleza no dia da angústia, e conhece os que confiam nele." — Naum 1:7',
  '"Não julgueis, para que não sejais julgados." — Mateus 7:1',
  '"Porque onde estiver o vosso tesouro, aí estará também o vosso coração." — Mateus 6:21',
  '"Peçam, e lhes será dado; busquem, e encontrarão; batam, e a porta lhes será aberta." — Mateus 7:7',
  '"Entrai pela porta estreita; porque larga é a porta, e espaçoso o caminho que conduz à perdição." — Mateus 7:13',
  '"O meu mandamento é este: Que vos ameis uns aos outros, assim como eu vos amei." — João 15:12',
  '"Vigiai, estai firmes na fé, portai-vos varonilmente, e fortalecei-vos." — 1 Coríntios 16:13',
  '"Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus." — 1 Coríntios 10:31',
  '"O choro pode durar uma noite, mas a alegria vem pela manhã." — Salmos 30:5',
  '"Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará." — Salmos 91:1',
  '"Sonda-me, ó Deus, e conhece o meu coração; prova-me, e conhece os meus pensamentos." — Salmos 139:23',
  '"Perto está o Senhor dos que têm o coração quebrantado, e salva os contritos de espírito." — Salmos 34:18',
  '"Os céus declaram a glória de Deus e o firmamento anuncia a obra das suas mãos." — Salmos 19:1',
  '"Grandes coisas fez o Senhor por nós, pelas quais estamos alegres." — Salmos 126:3',
  '"Esforçai-vos, e animai-vos; não temais, nem vos espanteis diante deles; porque o Senhor teu Deus é o que vai contigo." — Deuteronômio 31:6',
  '"Enganosa é a beleza e vã a formosura, mas a mulher que teme ao Senhor, essa sim será louvada." — Provérbios 31:30',
  '"O temor do Senhor é o princípio da sabedoria." — Provérbios 9:10',
  '"Como o ferro com ferro se aguça, assim o homem afia o rosto do seu amigo." — Provérbios 27:17',
  '"Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós." — 1 Pedro 5:7',
  '"Suportem-se uns aos outros e perdoem as queixas que tiverem uns contra os outros. Perdoem como o Senhor lhes perdoou." — Colossenses 3:13',
  '"Toda a Escritura é divinamente inspirada, e proveitosa para ensinar, para redarguir, para corrigir, para instruir em justiça." — 2 Timóteo 3:16',
  '"No princípio criou Deus os céus e a terra." — Gênesis 1:1',
  '"Ora, o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pela virtude do Espírito Santo." — Romanos 15:13',
  '"Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação." — 2 Timóteo 1:7',
  '"Em todo o tempo ama o amigo e para a hora da angústia nasce o irmão." — Provérbios 17:17',
  '"Ensina a criança no caminho em que deve andar, e ainda quando for velho, não se desviará dele." — Provérbios 22:6',
  '"Não amemos de palavra, nem de língua, mas por obra e em verdade." — 1 João 3:18',
  '"E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos pensamentos em Cristo Jesus." — Filipenses 4:7',
  '"Porque a palavra de Deus é viva e eficaz, e mais penetrante do que espada alguma de dois gumes." — Hebreus 4:12',
  '"Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança." — Gálatas 5:22',
  '"Confessai as vossas culpas uns aos outros, e orai uns pelos outros, para que sareis. A oração feita por um justo pode muito em seus efeitos." — Tiago 5:16',
  '"O que segue a justiça e a beneficência achará a vida, a justiça e a honra." — Provérbios 21:21',
  '"A soberba precede a ruína, e a altivez do espírito precede a queda." — Provérbios 16:18',
  '"Melhor é o pouco com o temor do Senhor, do que um grande tesouro onde há inquietação." — Provérbios 15:16',
  '"Não sejais vagarosos no cuidado; sede fervorosos no espírito, servindo ao Senhor." — Romanos 12:11',
  '"Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos." — Provérbios 16:3',
  '"O amigo ama em todos os momentos; é um irmão na adversidade." — Provérbios 17:17',
  '"Alegre-se o coração dos que buscam ao Senhor." — Salmos 105:3',
  '"Muitos são os planos no coração do homem, mas o que prevalece é o propósito do Senhor." — Provérbios 19:21',
  '"Não fui eu que lhe ordenei? Seja forte e corajoso! Não se apavore, nem se desanime, pois o Senhor, o seu Deus, estará com você por onde você andar." — Josué 1:9',
  '"E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus." — Romanos 8:28',
  '"O Senhor é o meu pastor; de nada terei falta." — Salmos 23:1',
  '"Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna." — João 3:16',
  '"As misericórdias do Senhor são a causa de não sermos consumidos, porque as suas misericórdias não têm fim." — Lamentações 3:22',
  '"Bem-aventurados os puros de coração, porque verão a Deus." — Mateus 5:8',
  '"Buscai ao Senhor enquanto se pode achar, invocai-o enquanto está perto." — Isaías 55:6',
  '"Eu sou o caminho, e a verdade e a vida; ninguém vem ao Pai, senão por mim." — João 14:6',
  '"Conhecereis a verdade, e a verdade vos libertará." — João 8:32',
  '"Bem-aventurado o varão que não anda segundo o conselho dos ímpios, nem se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores." — Salmos 1:1',
  '"O Senhor é a minha força e o meu escudo; nele o meu coração confia, e dele recebo ajuda." — Salmos 28:7',
  '"Respondeu Jesus: \'Amarás o Senhor teu Deus de todo o teu coração, e de toda a tua alma, e de todo o teu pensamento.\'" — Mateus 22:37',
  '"O próprio Senhor irá à sua frente e estará com você; ele nunca o deixará, nunca o abandonará." — Deuteronômio 31:8',
  '"Mil poderão cair ao seu lado; dez mil, à sua direita, mas nada o atingirá." — Salmos 91:7',
  '"A lei do Senhor é perfeita, e refrigera a alma." — Salmos 19:7',
  '"O Senhor é clemente e compassivo, paciente e transbordante de amor." — Salmos 145:8',
  '"Venham a mim, todos os que estão cansados e sobrecarregados, e eu darei descanso a vocês." — Mateus 11:28',
  '"O justo passa por muitas adversidades, mas o Senhor o livra de todas." — Salmos 34:19',
  '"Portanto, vão e façam discípulos de todas as nações, batizando-os em nome do Pai e do Filho e do Espírito Santo." — Mateus 28:19',
  '"Mas buscai primeiro o Reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas." — Mateus 6:33',
  '"O amor deve ser sincero. Odeiem o que é mau; apeguem-se ao que é bom." — Romanos 12:9',
  '"Aquele que é a Palavra estava no mundo, e o mundo foi feito por intermédio dele, mas o mundo não o reconheceu." — João 1:10',
  '"Ensina-nos a contar os nossos dias, de tal maneira que alcancemos corações sábios." — Salmos 90:12',
  '"A beleza de vocês não deve estar nos enfeites exteriores... Pelo contrário, esteja no ser interior, que não perece." — 1 Pedro 3:3-4',
  '"A riqueza de procedência vã diminuirá, mas quem a ajunta com o próprio trabalho a aumentará." — Provérbios 13:11',
  '"Melhor é o fim das coisas do que o princípio delas; melhor é o paciente de espírito do que o altivo de espírito." — Eclesiastes 7:8',
  '"Porque pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus." — Efésios 2:8',
  '"A sua benignidade dura para sempre." — Salmos 136:1',
  '"Deem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus." — 1 Tessalonicenses 5:18',
  '"Vistam-se com toda a armadura de Deus, para poderem ficar firmes contra as ciladas do diabo." — Efésios 6:11',
  '"Porque eu sou o Senhor, o teu Deus, que te toma pela tua mão direita e te diz: Não temas, eu te ajudo." — Isaías 41:13',
  '"Assim brilhe a luz de vocês diante dos homens, para que vejam as suas boas obras e glorifiquem ao Pai de vocês, que está nos céus." — Mateus 5:16',
  '"Em tudo, porém, somos mais que vencedores, por meio daquele que nos amou." — Romanos 8:37',
  '"Se vocês permanecerem em mim, e as minhas palavras permanecerem em vocês, pedirão o que quiserem, e lhes será concedido." — João 15:7',
  '"Ninguém tem maior amor do que aquele que dá a sua vida pelos seus amigos." — João 15:13',
  '"Por isso não desanimamos. Embora exteriormente estejamos a desgastar-nos, interiormente estamos sendo renovados dia após dia." — 2 Coríntios 4:16',
  '"A fé é a certeza daquilo que esperamos e a prova das coisas que não vemos." — Hebreus 11:1',
  '"Se alguém tem falta de sabedoria, peça a Deus, que a todos dá livremente, de boa vontade; e lhe será concedida." — Tiago 1:5',
  '"A resposta calma desvia a fúria, mas a palavra ríspida desperta a ira." — Provérbios 15:1',
  '"Aquele que é capaz de fazer infinitamente mais do que tudo o que pedimos ou pensamos..." — Efésios 3:20',
  '"Bem-aventurado o homem que suporta a provação, porque, depois de aprovado, receberá a coroa da vida." — Tiago 1:12',
  '"O que planta e o que rega têm um só propósito, e cada um será recompensado de acordo com o seu próprio trabalho." — 1 Coríntios 3:8',
  '"Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor." — Romanos 6:23',
  '"Tudo tem a sua ocasião, e há um tempo para todo propósito debaixo do céu." — Eclesiastes 3:1',
  '"Mas recebereis poder, ao descer sobre vós o Espírito Santo, e sereis minhas testemunhas." — Atos 1:8',
  '"Buscai o Senhor e o seu poder; buscai perpetuamente a sua presença." — 1 Crônicas 16:11',
  '"Elevarei os meus olhos para os montes, de onde vem o meu socorro." — Salmos 121:1',
  '"Não te indignes por causa dos malfeitores, nem tenhas inveja dos que praticam a iniquidade." — Salmos 37:1',
  '"No mundo tereis aflições, mas tende bom ânimo, eu venci o mundo." — João 16:33',
  '"Mas ele me disse: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza." — 2 Coríntios 12:9',
  '"Porque nele vivemos, e nos movemos, e existimos." — Atos 17:28',
  '"Deleita-te também no Senhor, e te concederá os desejos do teu coração." — Salmos 37:4',
  '"Entrega o teu caminho ao Senhor; confia nele, e ele o fará." — Salmos 37:5',
  '"Faze-me ouvir a tua benignidade pela manhã, pois em ti confio; faze-me saber o caminho que devo seguir, porque a ti levanto a minha alma." — Salmos 143:8',
  '"Porém, se vos parece mal aos vossos olhos servir ao Senhor, escolhei hoje a quem sirvais... porém eu e a minha casa serviremos ao Senhor." — Josué 24:15',
  '"Sede sóbrios; vigiai; porque o diabo, vosso adversário, anda em derredor, bramando como leão, buscando a quem possa tragar." — 1 Pedro 5:8',
  '"O Senhor pelejará por vós, e vós vos calareis." — Êxodo 14:14',
  '"Vós sois o sal da terra e a luz do mundo." — Mateus 5:13-14',
  '"Porque aos seus anjos dará ordem a teu respeito, para te guardarem em todos os teus caminhos." — Salmos 91:11',
  '"Ora, àquele que é poderoso para vos guardar de tropeços, e apresentar-vos irrepreensíveis, com alegria, perante a sua glória..." — Judas 1:24',
  '"Pela manhã ouvirás a minha voz, ó Senhor; pela manhã me apresentarei a ti, e vigiarei." — Salmos 5:3',
  '"Tu conservarás em paz aquele cuja mente está firme em ti; porque ele confia em ti." — Isaías 26:3',
  '"De sorte que haja em vós o mesmo sentimento que houve também em Cristo Jesus." — Filipenses 2:5',
  '"Posso todas as coisas naquele que me fortalece." — Filipenses 4:13',
  '"Ora, o nosso Deus é um fogo consumidor." — Hebreus 12:29',
  '"Vós sois a luz do mundo; não se pode esconder uma cidade edificada sobre um monte." — Mateus 5:14',
  '"Quem não ama não conhece a Deus; porque Deus é amor." — 1 João 4:8',
  '"Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós." — 1 Pedro 5:7',
  '"Confia no Senhor e faze o bem; habitarás na terra, e verdadeiramente serás alimentado." — Salmos 37:3',
  '"E a oração da fé salvará o doente, e o Senhor o levantará." — Tiago 5:15',
  '"Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize." — João 14:27',
  '"Criou Deus o homem à sua imagem, à imagem de Deus o criou; homem e mulher os criou." — Gênesis 1:27',
  '"Porque um menino nos nasceu, um filho se nos deu, e o principado está sobre os seus ombros." — Isaías 9:6',
  '"Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco." — 1 Tessalonicenses 5:18'
];
