export const RAP_QUOTES = [
  '"Fogo nos racistas, é o mínimo que a gente pede." — Djonga',
  '"O topo é pouco, eu quero o controle do que é meu." — Djonga',
  '"Dinheiro é bom, mas a paz de espírito é melhor ainda." — BK\'',
  '"Se o amanhã não for nada disso, caberá a mim esquecer." — BK\'',
  '"Injustiça atrai a fúria e o que é nosso nós vai buscar." — Racionais MC\'s',
  '"Vivão e vivendo, a rua é nóis, não é brincadeira." — Racionais MC\'s',
  '"Sonhar vicia, parar de sonhar me dá abstinência." — Emicida',
  '"Hoje eu sou dono do meu próprio império." — Filipe Ret',
  '"Eles querem meu fim, mas eu nasci pra ser o começo." — L7NNON',
  '"Ninguém é igual a ninguém, e essa é a nossa maior arma." — BK\'',
  '"A vida é um sopro, então não perde tempo com besteira." — Matuê',
  '"Sigo invicto, meu amor, quem sabe o que planta não teme a colheita." — Filipe Ret',
  '"Nós é a luz no fim do túnel." — Djonga',
  '"Coragem é a resistência ao medo, não a ausência dele." — BK\'',
  '"Nas noites mais escuras, as estrelas brilham mais." — Racionais MC\'s',
  '"Minha mente é meu guia, meu coração meu motor." — Filipe Ret',
  '"Vim pra deixar o meu legado, não pra agradar otário." — Djonga',
  '"Sou minha própria inspiração." — L7NNON',
  '"Avisa lá que o morro desceu e não é carnaval." — Racionais MC\'s',
  '"Foco, força e fé. O resto a gente corre atrás." — Projota',
  '"A rua é noiz, o resto é boato." — Emicida',
  '"O mundo é um moinho, mas a gente mói de volta." — Djonga',
  '"Crescer custa caro, o tempo é o preço." — BK\'',
  '"Se o mundo acabar amanhã, me acorde ao meio-dia." — BK\'',
  '"Malandragem de verdade é viver." — Sabotage',
  '"Para quem tem fé, a vida nunca tem fim." — Racionais MC\'s',
  '"E se eu cair, eu me levanto mais forte." — Djonga',
  '"Não tem como voltar no tempo, então faz o agora." — BK\'',
  '"Só quem é de lá sabe o que acontece lá." — Racionais MC\'s',
  '"Eles querem que você desista, mas eu não vou dar esse gostinho." — Filipe Ret',
  '"Onde o filho chora e a mãe não vê." — Racionais MC\'s',
  '"Até o maior dos prédios começa no chão." — Emicida',
  '"Deixa eles falarem, eu tô fazendo a minha parte." — L7NNON',
  '"Quem não é visto, não é lembrado. E quem não corre, não alcança." — Racionais MC\'s',
  '"Eu não mudei, eu só aprendi a jogar o jogo." — Djonga',
  '"A fé move montanhas, mas a atitude traz elas até você." — BK\'',
  '"Seja a mudança que você quer ver no mundo." — Emicida',
  '"Não sou o dono do mundo, mas sou o filho do dono." — Racionais MC\'s',
  '"A vida me ensinou a nunca desistir, ganhar, perder mas procurar evoluir." — Charlie Brown Jr / Sabotage',
  '"Pra quem já não tinha nada, metade é o dobro." — Emicida',
  '"Cada cicatriz é a prova de que eu sobrevivi." — Djonga',
  '"Quem tem boca vai a Roma, quem tem visão constrói o império." — Filipe Ret',
  '"A mente é um labirinto, eu sou o minotauro." — BK\'',
  '"A vida é loka, nêgo, e nela eu tô de passagem." — Racionais MC\'s',
  '"A dor ensina mais que qualquer professor." — Djonga',
  '"Se você não tentar, já perdeu antes de começar." — L7NNON',
  '"O que é meu tá guardado, e ninguém tira." — Filipe Ret',
  '"Tudo que nós tem é nós, então vamo se amar." — Emicida',
  '"O topo é solitário, mas a vista é linda." — BK\'',
  '"Não há vitória sem luta, não há glória sem dor." — Racionais MC\'s',
  '"A persistência é o caminho do êxito." — Djonga',
  '"Não deixo ninguém apagar o meu brilho." — L7NNON',
  '"A vida é curta, a arte é longa." — Emicida',
  '"O impossível é só questão de opinião." — Chorão',
  '"Sempre fui sonhador, é isso que me mantém vivo." — Racionais MC\'s',
  '"Eles riem de mim porque sou diferente, eu rio deles porque são todos iguais." — Filipe Ret',
  '"O tempo é o senhor de tudo, ele revela quem é quem." — BK\'',
  '"O amanhã é um mistério, hoje é uma dádiva." — Emicida',
  '"Se eu não puder ser o melhor, serei inesquecível." — Djonga',
  '"Nunca subestime o poder da favela." — Racionais MC\'s',
  '"A rua cobra, mas também ensina." — BK\'',
  '"Se a vida é um jogo, eu vim pra zerar." — L7NNON',
  '"O silêncio é de ouro, a palavra é de prata." — Filipe Ret',
  '"A esperança é a última que morre, mas a primeira que nasce." — Emicida',
  '"Não importa de onde você vem, importa pra onde você vai." — Djonga',
  '"O conhecimento é a única riqueza que ninguém pode roubar." — Racionais MC\'s',
  '"Eu sou o mestre do meu destino, o capitão da minha alma." — BK\'',
  '"A humildade é a chave do sucesso." — Emicida',
  '"O choro pode durar uma noite, mas a alegria vem pela manhã." — Racionais MC\'s',
  '"Se a vida te der limões, faça uma caipirinha." — Filipe Ret',
  '"O céu é o limite, e nós já estamos voando." — L7NNON',
  '"A verdadeira força vem de dentro." — Djonga',
  '"O amor é a arma mais poderosa." — Emicida',
  '"Nunca abaixe a cabeça pra ninguém." — Racionais MC\'s',
  '"O respeito é a base de tudo." — BK\'',
  '"A vitória é doce, mas o caminho é amargo." — Djonga',
  '"Acredite em si mesmo, quando ninguém mais acreditar." — Filipe Ret',
  '"A vida é um palco, e eu sou o protagonista." — L7NNON',
  '"A justiça tarda, mas não falha." — Racionais MC\'s',
  '"O futuro pertence àqueles que acreditam na beleza de seus sonhos." — Emicida',
  '"Eu sou o que sou, e não o que os outros querem que eu seja." — BK\'',
  '"A paciência é uma virtude." — Djonga',
  '"O sucesso é a melhor vingança." — Filipe Ret',
  '"A gratidão é a memória do coração." — Emicida',
  '"A vida é feita de escolhas." — Racionais MC\'s',
  '"O medo é apenas uma ilusão." — L7NNON',
  '"A coragem não é a ausência de medo, mas a ação apesar dele." — BK\'',
  '"O destino não é uma questão de sorte, é uma questão de escolha." — Djonga',
  '"A vida é como andar de bicicleta. Para ter equilíbrio, você tem que se manter em movimento." — Emicida',
  '"O sucesso não é final, o fracasso não é fatal: é a coragem de continuar que conta." — Filipe Ret',
  '"A jornada de mil milhas começa com um único passo." — BK\'',
  '"O que não nos mata, nos torna mais fortes." — Djonga',
  '"A maior glória em viver não está em nunca cair, mas em nos levantar toda vez que caímos." — Emicida',
  '"O único lugar onde o sucesso vem antes do trabalho é no dicionário." — L7NNON',
  '"A vida é 10% o que acontece com você e 90% como você reage a isso." — Racionais MC\'s',
  '"A mente é tudo. O que você pensa, você se torna." — BK\'',
  '"O melhor momento para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora." — Djonga',
  '"Não espere por líderes; faça você mesmo, pessoa por pessoa." — Emicida',
  '"A educação é a arma mais poderosa que você pode usar para mudar o mundo." — Racionais MC\'s'
];
